/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './server-transfer-state.module';
import * as import2 from './server-transfer-state';
import * as import3 from '@angular/platform-server';
import * as import4 from './transfer-state';
class ServerTransferStateModuleInjector extends import0.ɵNgModuleInjector<import1.ServerTransferStateModule> {
  _ServerTransferStateModule_0:import1.ServerTransferStateModule;
  __TransferState_1:import2.ServerTransferState;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _TransferState_1():import2.ServerTransferState {
    if ((this.__TransferState_1 == null)) { (this.__TransferState_1 = new import2.ServerTransferState(this.parent.get(import3.PlatformState),this.parent.get(import0.RendererFactory2))); }
    return this.__TransferState_1;
  }
  createInternal():import1.ServerTransferStateModule {
    this._ServerTransferStateModule_0 = new import1.ServerTransferStateModule();
    return this._ServerTransferStateModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ServerTransferStateModule)) { return this._ServerTransferStateModule_0; }
    if ((token === import4.TransferState)) { return this._TransferState_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ServerTransferStateModuleNgFactory:import0.NgModuleFactory<import1.ServerTransferStateModule> = new import0.NgModuleFactory<any>(ServerTransferStateModuleInjector,import1.ServerTransferStateModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTWFydGluL1Byb2plY3RzL2FuZ3VsYXI0LXNlcnZlcnNpZGUvc3JjL21vZHVsZXMvdHJhbnNmZXItc3RhdGUvc2VydmVyLXRyYW5zZmVyLXN0YXRlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9NYXJ0aW4vUHJvamVjdHMvYW5ndWxhcjQtc2VydmVyc2lkZS9zcmMvbW9kdWxlcy90cmFuc2Zlci1zdGF0ZS9zZXJ2ZXItdHJhbnNmZXItc3RhdGUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbbnVsbF0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
